import { ExportInput } from "./buildStarterPack";

export function buildProjectBundle(input: ExportInput) {
    const { idea, platform, businessModel, targetUsers, coreFeature, blueprint, displayMap } = input;

    // Feature detection helpers
    const allText = [...blueprint.features, ...blueprint.databaseTables].map(s => s.toLowerCase()).join(" ");
    const hasProfile = /auth|profile|user.?setting|account|login|signup|sign.?up/.test(allText);
    const hasActivity = /activity|log|notification|event|feed|timeline/.test(allText);
    const hasTeam = /team|collaborat|member|group|organization|workspace/.test(allText);

    const appLayoutContent = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${idea || "AppForge Project"}",
  description: "Starter project generated by AppForge",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`;

    const appPageContent = `import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-gray-950 text-white selection:bg-blue-500/30">
      <main className="text-center px-6 py-24 max-w-4xl mx-auto space-y-8">
        <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-white">
          ${idea || "Untitled Project"}
        </h1>
        <p className="text-xl text-gray-400 max-w-2xl mx-auto leading-relaxed">
          ${coreFeature || "A powerful new application."} Built for ${targetUsers || "everyone"}.
        </p>
        <div className="pt-8">
          <Link href="/dashboard">
            <Button variant="primary" className="rounded-full px-8 py-4 text-base shadow-lg shadow-blue-500/20">
              Get Started
            </Button>
          </Link>
        </div>
      </main>
    </div>
  );
}`;

    // Build dynamic sidebar links
    const navLinks = [
        `          <a href="/projects" className="block text-sm font-medium text-gray-400 hover:text-white transition-colors">Projects</a>`,
        `          <a href="/settings" className="block text-sm font-medium text-gray-400 hover:text-white transition-colors">Settings</a>`,
    ];
    if (hasProfile) navLinks.push(`          <a href="/profile" className="block text-sm font-medium text-gray-400 hover:text-white transition-colors">Profile</a>`);
    if (hasActivity) navLinks.push(`          <a href="/activity" className="block text-sm font-medium text-gray-400 hover:text-white transition-colors">Activity</a>`);
    if (hasTeam) navLinks.push(`          <a href="/team" className="block text-sm font-medium text-gray-400 hover:text-white transition-colors">Team</a>`);

    const dashboardPageContent = `import { StatCard } from "@/components/dashboard/stat-card";

export default function Dashboard() {
  return (
    <div className="flex min-h-screen bg-gray-900 text-white">
      <aside className="w-64 border-r border-white/10 p-6 hidden md:block bg-gray-900/50">
        <h2 className="text-xl font-bold mb-8 text-white">${idea || "App"}</h2>
        <nav className="space-y-4">
          <a href="#" className="block text-sm font-medium text-white">Overview</a>
${navLinks.join("\n")}
        </nav>
      </aside>
      <main className="flex-1 p-8 lg:p-12">
        <header className="mb-8 flex items-center justify-between">
            <h1 className="text-3xl font-bold tracking-tight text-white">Dashboard</h1>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
            <StatCard label="Total Users" value="0" />
            <StatCard label="Platform" value="${platform ? displayMap[platform] || platform : "Web App"}" helperText="Current target" />
        </div>

        <section>
            <h2 className="text-lg font-semibold text-white mb-4">Recent Activity</h2>
            <div className="bg-white/5 p-8 rounded-2xl border border-white/10 flex flex-col items-center justify-center text-center">
                <p className="text-gray-400 text-sm">No activity to display yet. Your ${businessModel ? displayMap[businessModel] || businessModel : "application"} is ready.</p>
            </div>
        </section>
      </main>
    </div>
  );
}`;

    const buttonComponentContent = `import * as React from "react";

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary";
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className = "", variant = "primary", ...props }, ref) => {
    const baseStyles = "inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-white/30 disabled:pointer-events-none disabled:opacity-50 active:scale-95";
    
    const variants = {
      primary: "bg-blue-600 text-white hover:bg-blue-700 shadow-sm",
      secondary: "bg-white/10 text-white hover:bg-white/20 border border-white/10"
    };
    
    return (
      <button
        ref={ref}
        className={\`\${baseStyles} \${variants[variant]} \${className}\`}
        {...props}
      />
    );
  }
);
Button.displayName = "Button";`;

    const typesContent = `export type Project = {
  id: string;
  title: string;
  platform: string;
  businessModel: string;
  targetUsers: string;
  coreFeature: string;
  createdAt: string;
};

export type User = {
  id: string;
  email: string;
  name?: string;
  role: "admin" | "user";
  createdAt: string;
};

export type DashboardStat = {
  label: string;
  value: number | string;
  trend?: string;
  trendDirection?: "up" | "down" | "neutral";
};`;

    const globalsCssContent = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: dark;
}

body {
  @apply bg-gray-950 text-white antialiased;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    "Helvetica Neue", Arial, sans-serif;
}

::selection {
  @apply bg-blue-500/30;
}

* {
  @apply border-white/10;
}`;

    const projectsPageContent = `import { projects } from "@/lib/mock-data";
import type { Project } from "@/lib/types";

export default function ProjectsPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight text-white">Projects</h1>
          <p className="mt-2 text-sm text-gray-400">
            Browse and manage your ${idea || "application"} projects.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {projects.map((project: Project) => (
            <div
              key={project.id}
              className="flex flex-col justify-between rounded-2xl border border-white/10 bg-white/5 p-6 shadow-sm backdrop-blur-sm transition-all hover:border-white/20"
            >
              <div>
                <div className="mb-3 flex items-center justify-between text-xs text-gray-500">
                  <span>{new Date(project.createdAt).toLocaleDateString()}</span>
                  <span className="rounded-full bg-white/10 px-2 py-1 text-gray-300">
                    {project.platform}
                  </span>
                </div>
                <h3 className="mb-2 text-lg font-semibold text-white">
                  {project.title}
                </h3>
                <p className="text-sm text-gray-400 line-clamp-2">
                  {project.coreFeature}
                </p>
              </div>
              <div className="mt-6">
                <button className="w-full rounded-full bg-white/10 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-white/20">
                  View Details
                </button>
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}`;

    const mockDataContent = `import type { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    id: "1",
    title: "${idea || "Core Platform"}",
    platform: "${platform ? displayMap[platform] || platform : "Web App"}",
    businessModel: "${businessModel ? displayMap[businessModel] || businessModel : "SaaS"}",
    targetUsers: "${targetUsers || "General users"}",
    coreFeature: "${coreFeature || "Main application feature"}",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "${idea ? idea + " v2" : "Mobile Companion"}",
    platform: "Mobile App",
    businessModel: "Free Tool",
    targetUsers: "${targetUsers || "Mobile users"}",
    coreFeature: "Companion app with push notifications and offline support",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "3",
    title: "${idea ? idea + " Admin" : "Admin Dashboard"}",
    platform: "Web App",
    businessModel: "Internal Tool",
    targetUsers: "Team administrators",
    coreFeature: "Analytics dashboard with user management and reporting",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
];`;

    const settingsPageContent = `export default function SettingsPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight text-white">Settings</h1>
          <p className="mt-2 text-sm text-gray-400">
            Manage your ${idea || "application"} preferences and configuration.
          </p>
        </div>

        <div className="space-y-6">
          <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
            <h2 className="text-lg font-semibold text-white mb-1">General</h2>
            <p className="text-sm text-gray-400 mb-4">Basic application settings.</p>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <span className="block text-sm font-medium text-gray-200">Project Name</span>
                  <span className="text-xs text-gray-500">The display name for your project</span>
                </div>
                <input
                  type="text"
                  defaultValue="${idea || "My Project"}"
                  className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-gray-200 outline-none focus:border-white/30 w-48"
                />
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <span className="block text-sm font-medium text-gray-200">Dark Mode</span>
                  <span className="text-xs text-gray-500">Toggle the interface theme</span>
                </div>
                <button className="rounded-full bg-blue-600 px-4 py-1.5 text-xs font-medium text-white">Enabled</button>
              </div>
            </div>
          </div>

          <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
            <h2 className="text-lg font-semibold text-white mb-1">Notifications</h2>
            <p className="text-sm text-gray-400 mb-4">Configure how you receive updates.</p>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <span className="block text-sm font-medium text-gray-200">Email Alerts</span>
                  <span className="text-xs text-gray-500">Get notified about important events</span>
                </div>
                <button className="rounded-full border border-white/20 bg-white/5 px-4 py-1.5 text-xs font-medium text-gray-400">Disabled</button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}`;

    const healthRouteContent = `import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    status: "ok",
    project: "${idea || "AppForge Project"}",
    platform: "${platform ? displayMap[platform] || platform : "Web App"}",
    timestamp: new Date().toISOString(),
  });
}`;

    const statCardContent = `interface StatCardProps {
  label: string;
  value: string | number;
  helperText?: string;
}

export function StatCard({ label, value, helperText }: StatCardProps) {
  return (
    <div className="bg-white/5 p-6 rounded-2xl border border-white/10 shadow-sm">
      <h3 className="text-sm font-medium text-gray-400 mb-2">{label}</h3>
      <p className="text-3xl font-bold text-white">{value}</p>
      {helperText && (
        <p className="mt-1 text-xs text-gray-500">{helperText}</p>
      )}
    </div>
  );
}`;

    // Conditional feature-based pages
    const profilePageContent = `export default function ProfilePage() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight text-white">Profile</h1>
          <p className="mt-2 text-sm text-gray-400">
            Manage your account and preferences for ${idea || "the application"}.
          </p>
        </div>

        <div className="space-y-6">
          <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
            <div className="flex items-center gap-4 mb-6">
              <div className="flex h-16 w-16 items-center justify-center rounded-full bg-blue-600 text-2xl font-bold text-white">
                U
              </div>
              <div>
                <h2 className="text-lg font-semibold text-white">User Name</h2>
                <p className="text-sm text-gray-400">user@example.com</p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="block text-xs font-semibold uppercase tracking-wider text-gray-500 mb-1">Role</span>
                <span className="text-gray-200">Admin</span>
              </div>
              <div>
                <span className="block text-xs font-semibold uppercase tracking-wider text-gray-500 mb-1">Member Since</span>
                <span className="text-gray-200">Today</span>
              </div>
            </div>
          </div>

          <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
            <h2 className="text-lg font-semibold text-white mb-4">Account Details</h2>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <span className="block text-sm font-medium text-gray-200">Display Name</span>
                  <span className="text-xs text-gray-500">How others see you</span>
                </div>
                <input type="text" defaultValue="User Name" className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-gray-200 outline-none focus:border-white/30 w-48" />
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <span className="block text-sm font-medium text-gray-200">Email</span>
                  <span className="text-xs text-gray-500">Your account email address</span>
                </div>
                <input type="email" defaultValue="user@example.com" className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-gray-200 outline-none focus:border-white/30 w-48" />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}`;

    const activityPageContent = `const recentActivity = [
  { id: "1", action: "Project created", target: "${idea || "New Project"}", time: "Just now" },
  { id: "2", action: "Blueprint generated", target: "Version 1.0", time: "2 minutes ago" },
  { id: "3", action: "Settings updated", target: "Notifications", time: "1 hour ago" },
  { id: "4", action: "Export completed", target: "Project bundle", time: "3 hours ago" },
  { id: "5", action: "Team member invited", target: "collaborator@email.com", time: "Yesterday" },
];

export default function ActivityPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight text-white">Activity</h1>
          <p className="mt-2 text-sm text-gray-400">
            Recent events and actions in your ${idea || "application"}.
          </p>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/5 overflow-hidden">
          <ul className="divide-y divide-white/5">
            {recentActivity.map((item) => (
              <li key={item.id} className="flex items-center justify-between px-6 py-4 hover:bg-white/5 transition-colors">
                <div>
                  <p className="text-sm font-medium text-white">{item.action}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{item.target}</p>
                </div>
                <span className="text-xs text-gray-500 whitespace-nowrap">{item.time}</span>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </div>
  );
}`;

    const teamPageContent = `const teamMembers = [
  { id: "1", name: "Project Owner", email: "owner@example.com", role: "Admin", avatar: "PO" },
  { id: "2", name: "Developer", email: "dev@example.com", role: "Editor", avatar: "DE" },
  { id: "3", name: "Designer", email: "design@example.com", role: "Viewer", avatar: "DS" },
];

export default function TeamPage() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <main className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-white">Team</h1>
            <p className="mt-2 text-sm text-gray-400">
              Manage collaborators on ${idea || "your project"}.
            </p>
          </div>
          <button className="rounded-full bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-700 transition-colors">
            Invite Member
          </button>
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {teamMembers.map((member) => (
            <div key={member.id} className="rounded-2xl border border-white/10 bg-white/5 p-6 text-center">
              <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-blue-600/20 text-lg font-bold text-blue-400">
                {member.avatar}
              </div>
              <h3 className="text-sm font-semibold text-white">{member.name}</h3>
              <p className="text-xs text-gray-400 mt-1">{member.email}</p>
              <span className="mt-3 inline-block rounded-full bg-white/10 px-3 py-1 text-xs font-medium text-gray-300">
                {member.role}
              </span>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}`;

    // Build the files object with conditional pages
    const files: Record<string, string> = {
        "README.md": `# Project Overview\n\n${idea || "No idea provided"}\n\n## Target Users\n${targetUsers || "Not provided"}\n\n## Core Feature\n${coreFeature || "Not provided"}\n\n## Suggested Tech Stack\n${blueprint.techStack.map(t => `- ${t}`).join("\n")}`,
        "docs/PROJECT_SPEC.md": `# Project Specification\n\n**App Idea:**\n${idea || "Not provided"}\n\n**Platform:**\n${platform ? displayMap[platform] || platform : "Not provided"}\n\n**Business Model:**\n${businessModel ? displayMap[businessModel] || businessModel : "Not provided"}\n\n**Target Users:**\n${targetUsers || "Not provided"}\n\n**Core Feature:**\n${coreFeature || "Not provided"}\n\n**Features Summary:**\n${blueprint.features.map(f => `- ${f}`).join("\n")}`,
        "docs/DATABASE_SCHEMA.md": `# Database Schema\n\n${blueprint.databaseTables.map(t => `- ${t}`).join("\n")}`,
        "docs/API_ROUTES.md": `# API Routes\n\n${blueprint.apiRoutes.map(r => `- ${r}`).join("\n")}`,
        "docs/TASKS.md": `# Tasks & Roadmap\n\n## Roadmap\n${blueprint.roadmap.map(r => `- [ ] ${r}`).join("\n")}\n\n## Features to Implement\n${blueprint.features.map(f => `- [ ] ${f}`).join("\n")}`,
        "app/globals.css": globalsCssContent,
        "app/layout.tsx": appLayoutContent,
        "app/page.tsx": appPageContent,
        "app/dashboard/page.tsx": dashboardPageContent,
        "app/projects/page.tsx": projectsPageContent,
        "app/settings/page.tsx": settingsPageContent,
        "app/api/health/route.ts": healthRouteContent,
        "components/ui/button.tsx": buttonComponentContent,
        "components/dashboard/stat-card.tsx": statCardContent,
        "lib/types.ts": typesContent,
        "lib/mock-data.ts": mockDataContent,
    };

    if (hasProfile) files["app/profile/page.tsx"] = profilePageContent;
    if (hasActivity) files["app/activity/page.tsx"] = activityPageContent;
    if (hasTeam) files["app/team/page.tsx"] = teamPageContent;

    return {
        projectName: idea || "appforge-project",
        idea: idea || "",
        platform: platform || "",
        businessModel: businessModel || "",
        targetUsers: targetUsers || "",
        coreFeature: coreFeature || "",
        generatedBlueprint: blueprint,
        files
    };
}
