import { ExportInput } from "./buildStarterPack";
import { buildProjectBundle } from "./buildProjectBundle";
import { buildMarkdownFiles } from "./buildMarkdownFiles";

/**
 * Orchestrates all individual builders into a single comprehensive file map
 * for a full starter project repository.
 */
export function buildFullProject(input: ExportInput): Record<string, string> {
    const { idea, blueprint } = input;

    // 1. Generate core project structure using existing bundle logic
    // This already includes API routes, DB schema, types, mock data, and feature modules
    const bundle = buildProjectBundle(input);
    const files = { ...bundle.files };

    // 2. Generate specialized markdown documentation
    const markdownFiles = buildMarkdownFiles(input);
    for (const file of markdownFiles) {
        // Prefix with docs/ if not already or use the specified name
        // Our buildMarkdownFiles currently returns { name: 'appforge-README.md', ... }
        // We'll map them to standard locations
        if (file.name === "appforge-README.md") {
            // README.md is already generated by buildProjectBundle, but we'll override it
            // with a potentially more detailed version if needed, or stick to the one in bundle.
            // For v1, let's ensure we have a robust README.
            files["README.md"] = file.content;
        } else if (file.name === "appforge-PROJECT_SPEC.md") {
            files["docs/architecture.md"] = file.content;
        }
    }

    // 3. Generate a comprehensive roadmap in docs
    if (blueprint.roadmap && blueprint.roadmap.length > 0) {
        files["docs/roadmap.md"] = `# Development Roadmap\n\n${blueprint.roadmap.map(r => `- [ ] ${r}`).join("\n")}`;
    }

    // 4. Generate package.json
    const slug = (idea || "appforge-app")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");

    const packageJson = {
        name: slug,
        version: "0.1.0",
        private: true,
        scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint"
        },
        dependencies: {
            "next": "latest",
            "react": "latest",
            "react-dom": "latest",
            "lucide-react": "latest",
            "clsx": "latest",
            "tailwind-merge": "latest"
        },
        devDependencies: {
            "typescript": "latest",
            "@types/node": "latest",
            "@types/react": "latest",
            "@types/react-dom": "latest",
            "autoprefixer": "latest",
            "postcss": "latest",
            "tailwindcss": "latest"
        }
    };

    files["package.json"] = JSON.stringify(packageJson, null, 2);

    // TODO: Add .gitignore
    // TODO: Add tailwind.config.ts
    // TODO: Add tsconfig.json

    return files;
}
